services:
  web:  
    build: ./php-apache/
    container_name: php-apache-container
    ports:
      - 3000:80
    links:
      - database
    volumes:
      - ./public-html/:/var/www/html/

  database:  
    image: mysql:5.7
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    ports:
      - 8080:80
    links:
      - database
    environment:
      PMA_HOST: 127.0.0.1
      PMA_PORT: 3306
volumes:
  database:
    driver: local
